[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
hyper = { version = "0.14.27", features = ["full"] }
hyper-tls = "0.5.0"
tokio = { version = "1.29.1", features = ["full"] }
